# Site settings
title: Jules Simplicio
email: hi@julessimplic.io
description: Software product designer and developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://julessimplic.io" # the base hostname & protocol for your site
twitter_username: julessimplicio
github_username:  jsimplicio

# Compile settings
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md, vendor]

# Build settings
markdown: kramdown
plugins: [autoprefixer-rails]
permalink: /:categories/:title/

# Variables
data:
  subtitle: ""

sass:
  style: compressed
  sass_dir: _sass

navigation:
  - title: home
    url: /
  - title: about
    url: /about
  - title: work
    url: /work