# Site settings
title: Jules Simplicio
email: hi@jules.studio
description: Product development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jsimplicio.github.io" # the base hostname & protocol for your site
twitter_username: julessimplicio
github_username:  jsimplicio

# Compile settings
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

# Build settings
markdown: kramdown
gems: [autoprefixer-rails]
permalink: /:categories/:title/

# Variables
data:
  tags: ""
  subtitle: ""

navigation:
  - title: home
    url: /index.html

sass:
  style: compressed
  sass_dir: ../../../assets/stylesheets
