# Site settings
title: Jules Simplicio
email: hi@julessimplic.io
description: Software product designer and developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://julessimplic.io" # the base hostname & protocol for your site
twitter_username: julessimplicio
github_username:  jsimplicio

# Compile settings
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md, vendor]

# Build settings
markdown: kramdown
plugins: [autoprefixer-rails, jekyll-paginate-v2]
permalink: /:categories/:title/

# Variables
data:
  subtitle: ""

navigation:
  - title: home
    url: /index.html

sass:
  style: compressed
  sass_dir: _sass

pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: '/page/:num/'
  title: ':title — Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
